### PR TITLE
Reduce notifications for a minor speedup

### PR DESCRIPTION
**Pull request by x42005e1f**
Avoids calling slow notification methods when there are no waiters.

### CODE REVIEW

**Comment by x42005e1f** [comment]
In fact, false positive cases are possible (the number of waiters is higher than it actually is), since the thread must enter the finally block to decrement. But access to the waiting queue requires access to the undocumented Condition attribute, which may break in future versions of Python or other implementations of the standard library. Therefore, the number of notifications is not optimal.

**Comment by x42005e1f** [comment]
Update: ~9.5|1.4|2.3|10.2x speedup according to new janus benchmarks (aa8353c)

**Comment by asvetlov** [comment]
Thanks, the speedup looks very impressive!
I'll take a careful review after sleeping on the PR.

**Comment by asvetlov** [comment]
@x42005e1f thank you for adding more tests! I'm out of my laptop right now, I'll review the PR again when I come back.

**Review by asvetlov — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
