### PR TITLE
accept loop parameter for Queue

### PR DESCRIPTION
**Pull request by ali5h**
## What do these changes do?

Use case: If one wants to create the Queue in the main thread of the app, but use
it with an async loop that is running in a thread (not the one in the main thread).

Otw. one would have to create the queue in the thread to pick up the correct loop.

## Are there changes in behavior for the user?

no change in behavior if used as before. Now user can pass a custom loop.

## Checklist

- [x] I think the code is well written
- [x] Add a new news fragment into the `CHANGES` folder

---
This change is [Reviewable](https://reviewable.io/reviews/aio-libs/janus/297)

### CODE REVIEW

**Comment by asvetlov** [comment]
Your request is error-prone, sorry.
The loop should not be transferred between threads, this is the rule of thumb.

**Comment by ali5h** [comment]
then how do you want to run the queue in its own thread?

**Comment by asvetlov** [comment]
Create a queue instance in that thread than, that is what I can suggest

**Comment by ali5h** [comment]
yes, that is exactly the issue, many of python async functions accept loop parameter, what is error prone about this?

**Comment by asvetlov** [comment]
In asyncio from Python 3.10 only two such public functions are left, all others were deprecated the loop argumemr by 3.8 and removed in 3.10

**Comment by ali5h** [comment]
the problem is `janus` is asking for a running loop, which cannot be started yet.

**Comment by asvetlov** [comment]
The latest janus maybe doesn't fit your (not published) code, sure.
But I'm also sure that the code can be modified to satisfy the latest janus design.
Thus I cannot name it the "problem".

**Comment by brianbienvenu** [comment]
@ali5h Thanks for this snippet. I setup a new system with old Python 3.7 code & janus 0.4.0 on Python 3.8 & janus 0.6.1, and this was the only change which bit me. Patched the janus __init__.py with the suggested change and it works fine - good enough for another handful of years.

I'm sure this isn't best practice asyncio use for modern Python, but it's a lot lower friction than upgrading the rest of the codebase.

**Pull request closed without merging**
